### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by marjasin123** [dawguk/php-garmin-connect#12]
I have been using this wonderful script for a while now but now suddenly I get an error: "Oops: "lt" value wasn't found in response"

Did garmin change the authentication somehow and could you provide a fix?

**Comment by mgnwong** [comment]
The Garmin Development Team must've changed the authentication. 
I'll provide you with the fix as soon as I find it.

**Comment by dawguk** [comment]
Looks like Garmin have changed something, yep. Unsure what yet, but as the
authentication code was looking for specific items in the page (a sort of
screen scrape if you like), the authentication method was always prone to
this sort of failure.

Miguel, I'll take a look too, but if you beat me to it, that's also good ;)

FYI, this method was lifted from Tapiriik, so it might be worth taking a
look at their github to see if they've found a solution yet.


On 14 Dec 2016 6:00 p.m., "Miguel Angel Wong" <notifications@github.com>
wrote:

The Garmin Development Team must've changed the authentication.
I'll provide you with the fix as soon as I find it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dawguk/php-garmin-connect/issues/12#issuecomment-267106598>,
or mute the thread

**Comment by marjasin123** [comment]
tapiriik source was not changed for 2 months and their garmin service on https://tapiriik.com does not work at the moment
