### ISSUE TITLE
http 402

### ISSUE THREAD

**Issue by stigc** [dawguk/php-garmin-connect#48]
Anyone else getting this? 

Fatal error: Uncaught dawguk\GarminConnect\exceptions\UnexpectedResponseCodeException: An unexpected response code was found: 402
 
402 is Payment Required, seems like they are blocking requests from my IP.

**Comment by e7andy** [comment]
Yes. I was just about to report it as well. I started testing this code just because changed the access to the services for a couple of days ago which broke my service. I hoped that this code would solve it, but it ran into the same issue as I did.

Here is a discussion in Garmin Forums: https://forums.garmin.com/apps-software/mobile-apps-web/f/garmin-connect-web/255422/connect-api-authentication-problems

**Comment by e7andy** [comment]
When I inspected the requests in Garmin Connect I saw that an extra header was added: `-H 'nk: NT'`
I modified the code in Connector.php in both the get() and post() functions and added:
`$headers[] = 'nk: NT';`
In the get method I also had to set the headers to curl:
`curl_setopt($this->objCurl, CURLOPT_HTTPHEADER, $headers);`

That actually makes everything work for me.

Do some tests and see if that helps.

**Comment by cabby26** [comment]
It works for me

**Comment by ltcomd** [comment]
Thanks, works for me, too.

**Comment by LEstefano** [comment]
Thank you e7andy, it works like a charm!

**Comment by pygoubet** [comment]
Just proposing a PR #49

**Comment by dawguk** [comment]
Thanks all for the work, this has now been fixed in release v1.6.0 (https://github.com/dawguk/php-garmin-connect/compare/v1.5.0...v1.6.0)
